name: superheroes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^4.0.0
  network_image_mock: ^2.1.1
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1
  golden_toolkit: ^0.14.0


flutter:


  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env
